<?php
echo $this->headTitle('Add new Pizza');
?>

<h1>Add new Pizza</h1>

<?php
   $form = $this->form;
   $form->setAttribute('action', $this->url('pizza', array('action' => 'add')));
   $form->prepare();
   
   echo $this->form()->openTag($form);
   echo $this->formRow($form->get('pizzaname')) . '<br />';
   echo $this->formRow($form->get('ingredients')) . '<br />';
   echo $this->formRow($form->get('add_pizza')) . '<br />';
   echo $this->form()->closeTag();
    
?>