<?php

$title = 'Delete User';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete 
    '<?php echo $this->escapeHtml($user->username); ?>' from
    '<?php echo $this->escapeHtml($user->cat); ?>' 
</p>

<?php
    $url = $this->url('users', array(
       'action' => 'delete',
       'id'     => $this->id,
    ));
?>

<form action="<?php echo $url; ?>" method="post">
    <input type="submit" value="Yes" name="del" />
    <input type="submit" value="No" nam="del" />
    <input type="hidden" name="id" value="<?php echo $user->id; ?>" />
 </form>