<?php

$title = 'Edit User';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
        'users', 
        array(
                'action' => 'edit',
                'id'     => $this->id,
            )
        )
    );
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('cat'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
