<?php

$title = 'Users List';
$this->headTitle($title);
?>
<script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action' => 'add')); ?>">Add new user</a>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>User</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->username); ?></td>
        <td><?php echo $this->escapeHtml($user->cat); ?></td>
        <td><a href="<?php echo $this->url('users', array('action' => 'edit', 'id' => $user->id)); ?>">Edit</a></td>
        <td><a href="<?php echo $this->url('users', array('action' => 'delete', 'id' => $user->id)); ?>">Delete</a></td>
    </tr>
    <?php endforeach; ?>
</table>
