<?php

$title = 'Users List';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action' => 'add')); ?>">Add new user</a>
</p>

<table class='table'>
    <tr>
        <th>Title</th>
        <th>User</th>
    </tr>
    <?php foreach($users as $user) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->username); ?></td>
        <td><?php echo $this->escapeHtml($user->cat); ?></td>
    </tr>
    <?php endforeach; ?>
</table>