<?php

$title = 'Users List';
$this->headTitle($title);
?>
<script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('users', array('action' => 'add')); ?>">Add new user</a>
</p>
<?php
$user_username = array();
$user_cat = array();
foreach($users as $user) : 
    $user_username[] = $user->username;
 endforeach;

 ?>
<table ng-app="" ng-init="names=[<?php echo implode(',',$user_username); ?> ]" class='table'>
    <tr>
        <th>Title</th>
        <th>User</th>
    </tr>
    <tr ng-repeat="x in names">
        <td>{{ x }}</td>
    </tr>
</table>
